# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: sendNotificationToCDD@0
  inputs:
    cddEndpoint: 'CDD-TEST-NEW'
    application: 'repoNameAsApplicationName'
    applicationVersion: 'branchNameAsVersion'
    cddTokens: '{"BUILD_NAME":"$(Build.DefinitionName)","PROJECT":"$(System.TeamProject)"}'
    commitSource: '{"itemsToReturn":"1,2,7,8"}'
    testData: |
      [
          {
            "name": "DemoTSTemplate",
            "parameters": {"branch":"master"}
          }
       ]
    notificationExecutionStrategy: 'createRelease'
    dslSource: 'fileSource'
    fileSourceName: 'GithubFS'
    dslFilename: 'CDD-FileSource/relWithAppVerBranch.json'
    fileSourceParameters: '{"branch":"master"}'
    dslParameter: '{ "appName": "DEMO-APP", "appVerName": "1.0", "relName": "new-release-12", "envName": "DEV" }'